redis:
  image: redis
  ports:
    - "6379:6379"
rabbitmq:
  image: rabbitmq
  ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
mongo:
  image: mongo
  ports:
    - "27017:27017"
postgres:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=metrics
    - POSTGRES_PASSWORD=foobar
