# Workers
hourlylog:
  build: .
  restart: always
  command: app -debug hourlylog
  environment:
    - MONGO_URL=mongo:27017
    - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
  links:
    - mongo:mongo
    - rabbitmq:rabbitmq
distinctname:
  build: .
  restart: always
  command: app -debug distinctname
  environment:
    - REDIS_URL=redis:6379
    - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
  links:
    - redis:redis
    - rabbitmq:rabbitmq
accountname:
  build: .
  restart: always
  command: app -debug accountname
  environment:
    - POSTGRES_URL=postgres://metrics:foobar@postgres/metrics?sslmode=disable
    - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
  links:
    - postgres:postgres
    - rabbitmq:rabbitmq

# Backends
redis:
  image: redis
  ports:
    - "6379:6379"
rabbitmq:
  image: rabbitmq
  ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
mongo:
  image: mongo
  ports:
    - "27017:27017"
postgres:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=metrics
    - POSTGRES_PASSWORD=foobar
    - POSTGRES_DB=metrics
